# Unit duration in seconds for one audio segment
unit_sec: 0.95
# FFT parameters
sample_rate: 16000
n_fft: 1024
win_length: 400
hop_length: 160
n_mels: 64
f_min: 60
f_max: 7800
# vit encoder
use_cls: true
patch_size: [16, 16]